---

- name: print qmgr name
  ansible.builtin.command: echo "{{ qmgr_name }}"
  register: qmgrname

- debug:
   var: qmgrname.stdout

- name: Create MQ Queue Manager 
  become: true
  tasks:
    - name: create task
      command: "{{ item }}"
      with_items: 
        - sudo su - mqm
        #- crtmqm -lc -lf 1024 -lp 3 -ls 2 -p 2022 -u .DLQ "{{ qmgr_name }}"
      register: crt_cmd   

- debug:
   var: crt_cmd.stdout

- name: verify status
  ansible.builtin.command: dspmq -m "{{ qmgr_name }}"
  register: command_output

- debug: msg="The status of QMGR {{ qmgr_name }} is:{{ command_output.stdout }}" 
    


#- name: Copy MQ queue manager config
#  copy:
#   src: METDEV.QUE.MGR.mqsc
#   dest: /var/mqm/config/
