---

#- name: print qmgr name
#  ansible.builtin.command: echo {{ qmgr_name }}
#  register: qmgrname

#- debug:
#   var: qmgrname.stdout

- name: create task
  become: true
  ansible.builtin.command: su - mqm -c "crtmqm -lc -u .DLQ {{ qmgr_name }}"

- name: verify status
  ansible.builtin.command: dspmq -m {{ qmgr_name }}
  register: command_output

- debug: msg="Queue Manager {{ qmgr_name }} Created successful. Status:{{ command_output.stdout }}" 
