---

- name: print qmgr name
  ansible.builtin.command: echo {{ qmgr_name }}
  register: qmgrname

- debug:
   var: qmgrname.stdout

- name: create task
  ansible.builtin.shell: | 
    - crtmqm -lc -u .DLQ { qmgr_name }
  register: crt_cmd   

- debug:
   var: crt_cmd.stdout

- name: verify status
  ansible.builtin.command: dspmq -m {{ qmgr_name }}
  register: command_output

- debug: msg="The status of QMGR {{ qmgr_name }} is:{{ command_output.stdout }}" 
    


#- name: Copy MQ queue manager config
#  copy:
#   src: METDEV.QUE.MGR.mqsc
#   dest: /var/mqm/config/
