---

- name: verify status
  ansible.builtin.command:  dspmq -m {{ qmgr_name }}
  register: command_output

- debug: msg="Queue Manager started successful. Status:{{ command_output.stdout }}" 

#- name: Create MQ QMGRs Listeners
#  ansible.builtin.command: su - mqm -c "echo 'DEF LISTENER({{ qmgr_name }}.LSNR) TRPTYPE(TCP) PORT({{ lstnr_port }}) CONTROL(QMGR)'' | runmqsc {{ qmgr_name }}"

