---

- name: Starting queue Manager {{ qmgr_name }}
  become: true
  ansible.builtin.command: su - mqm -c "strmqm {{ qmgr_name }}"

- name: verify status
  become: true
  ansible.builtin.command:  su - mqm -c "dspmq -m {{ qmgr_name }}"
  register: command_output

- debug: msg="Queue Manager {{ qmgr_name }} started successful. Status:{{ command_output.stdout }}" 
