---

# Get list of packages from file
- name: List install packages for Broker Node
  shell:  cat /softwares/MQ_and_ESB_BRK/install_files/broker_inst_packages.txt
  register: psout

-  name: check files
   ansible.builtin.shell: |
     cd /softwares/MQ_and_ESB_BRK/MQ9.3_upgrade/MQ9.3/MQServer/
     sudo rpm --import /softwares/MQ_and_ESB_BRK/MQ9.3_upgrade/MQ9.3/MQServer/ibm_mq_public.pgp
     sudo rpm -Kv /softwares/MQ_and_ESB_BRK/MQ9.3_upgrade/MQ9.3/MQServer/MQSeriesRuntime-9.3.0-0.x86_64.rpm
     sudo /usr/bin/sh /softwares/MQ_and_ESB_BRK/MQ9.3_upgrade/MQ9.3/MQServer/mqlicense.sh -accept 
   register: lic_out
   
- debug:
   var: {{ lic_out|to_json }}


#- debug:
#   var: psout.stdout

# Set file path
#-  name:  Set file path for rpms
##   find: 
##     paths: /softwares/MQ_and_ESB_BRK/MQ9.3_upgrade/MQ9.3/MQServer
#     patterns: "*.rpm"
#   register: rpm_files

# Create a list of RPM's to use with rpm install command
#- set_fact:
#    rpm_list: "{{ rpm_files.files | map(attribute='path') | list }}"

#- debug:
#   var: rpm_files

#- name: Show result
#  debug:
#    msg: "{{ rpm_files }}"

#- name: Get list of packages from file and list from directory
#  ansible.builtin.command: rpm -Uvh /softwares/MQ_and_ESB_BRK/MQ9.3_upgrade/MQ9.3/MQServer/'{{ rpm_list }}'
#  loop: 
#    - "{{ lookup('file', filepath) }}"
#  vars:
#    filepath: ./install_packages.txt