---

# Get list of packages from file
- name: List install packages for Broker Node
  shell:  cat /softwares/MQ_and_ESB_BRK/install_files/broker_inst_packages.txt
  register: psout

-  name: check files
   ansible.builtin.shell: |
     cd /softwares/MQ_and_ESB_BRK/MQ9.3_upgrade/MQ9.3/MQServer/
     sudo rpm --import /softwares/MQ_and_ESB_BRK/MQ9.3_upgrade/MQ9.3/MQServer/ibm_mq_public.pgp
   register: lic_out
   
- debug:
   var: lic_out.stdout

# Proceed with MQ installation
- name: Install MQ BASE 
  ansible.builtin.shell: |
    while read line; do sudo rpm -Uvh /softwares/MQ_and_ESB_BRK/9.3_fx/$line ;  done <  /softwares/MQ_and_ESB_BRK/install_files/install_gateway_packages.txt
    sudo /opt/mqm/bin/setmqinst -n Installation1 -p /opt/mqm -i
  register: inst_cmd

- debug:
   var: inst_cmd.stdout

#Get installed packages
- name: Install MQ BASE 
  ansible.builtin.command: sudo rpm -qa | grep -i mqser*
  register: pkg_inst

- debug:
   var: pkg_inst.stdout